apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: hpc-nodes
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-qkc2m-qs978
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-qkc2m-qs978
      machine.openshift.io/cluster-api-machineset: hpc-nodes
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-qkc2m-qs978
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: hpc-nodes
    spec:
      taints:
      - effect: NoSchedule
        key: hpc
        value: hpc
      lifecycleHooks: {}
      metadata: 
        labels:
          purpose: hpc
      providerSpec:
        value:
          userDataSecret:
            name: worker-user-data
          placement:
            availabilityZone: us-east-2c
            region: us-east-2
          credentialsSecret:
            name: aws-cloud-credentials
          instanceType: c6i.24xlarge
          metadata:
            creationTimestamp: null
          blockDevices:
            - ebs:
                encrypted: true
                iops: 0
                kmsKey:
                  arn: ''
                volumeSize: 100
                volumeType: gp3
          securityGroups:
            - filters:
                - name: 'tag:Name'
                  values:
                    - cluster-qkc2m-qs978-worker-sg
          kind: AWSMachineProviderConfig
          metadataServiceOptions: {}
          tags:
            - name: kubernetes.io/cluster/cluster-qkc2m-qs978
              value: owned
            - name: env_type
              value: ocp4-cluster
            - name: guid
              value: qkc2m
            - name: owner
              value: unknown
            - name: platform
              value: RHPDS
            - name: uuid
              value: 5bb0c0b1-ebd8-59b8-8357-6d42dc0a8423
            - name: Stack
              value: project ocp4-cluster-qkc2m
          deviceIndex: 0
          ami:
            id: ami-0ff64f495c7e977cf
          subnet:
            filters:
              - name: 'tag:Name'
                values:
                  - cluster-qkc2m-qs978-private-us-east-2c
          apiVersion: machine.openshift.io/v1beta1
          iamInstanceProfile:
            id: cluster-qkc2m-qs978-worker-profile
