apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foam-tutorials-claim
spec:
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi