---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: openshift-storage
  name: openshift-storage
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-storage-og
  namespace: openshift-storage
spec:
  targetNamespaces:
  - openshift-storage
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription        
metadata:   
  name: odf-operator                          
  namespace: openshift-storage    
  labels:                             
    operators.coreos.com/odf-operator.openshift-storage: "" 
spec:                            
  channel: stable-4.9
  installPlanApproval: Automatic
  name: odf-operator                          
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: odf-operator.v4.9.1
---
apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  name: odf-console
spec:
  displayName: ODF Plugin
  service:
    basePath: /
    name: odf-console-service
    namespace: openshift-storage
    port: 9001
