apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: openfoam-testjob
spec:
  slotsPerWorker: 1
  sshAuthMountPath: /home/openfoam/.ssh
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: quay.io/openshiftdemos/kubeflow-mpi-openfoam:latest
            name: foam-container
            command:
            - mpirun
            args:
            - --allow-run-as-root
            - -np
            - "2"
            - icoFoam
            - -parallel
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - image: quay.io/openshiftdemos/kubeflow-mpi-openfoam:latest
            name: foam-worker
            command:
            - /usr/sbin/sshd
            args:
            - -De
            - -f
            - /home/openfoam/.sshd_config