apiVersion: v1
kind: ConfigMap
metadata:
  name: wing-job
data:
  wing.sh: |
    #!/bin/bash
    echo "STARTING"
    date
    START="$(date +%s)"
    source /opt/openfoam9/etc/bashrc
    cd /home/openfoam/storage/wingTemplate
    set -x
    set -e
    surfaceConvert ./constant/Input/wing.stl ./constant/triSurface/wing.stl -clean -scale 0.0254
    surfaceFeatures
    blockMesh
    decomposePar -copyZero -force
    mpirun -np 512 -mca orte_base_help_aggregate 0 snappyHexMesh -overwrite -parallel -case /home/openfoam/storage/wingTemplate
    mpirun -np 512 renumberMesh -overwrite -parallel -case /home/openfoam/storage/wingTemplate
    mpirun -np 512 checkMesh -parallel -case /home/openfoam/storage/wingTemplate
    mpirun -np 512 splitMeshRegions -largestOnly -overwrite -case /home/openfoam/storage/wingTemplate
    mpirun -np 512 checkMesh -case /home/openfoam/storage/wingTemplate
    mpirun -np 512 patchSummary -parallel -case /home/openfoam/storage/wingTemplate
    mpirun -np 512 potentialFoam -parallel -case /home/openfoam/storage/wingTemplate
    mpirun -np 512 simpleFoam -parallel -case /home/openfoam/storage/wingTemplate
    set +x
    date
    echo "ENDED"
