apiVersion: v1
kind: ConfigMap
metadata:
  name: dambreak-job
data:
  damBreak.sh: |
    #!/bin/bash
    echo "STARTING"
    date
    START="$(date +%s)"
    source /opt/openfoam9/etc/bashrc
    cd /home/openfoam/storage/examples/damBreak
    set -x
    set -e
    mpirun -np 4 interFoam -case /home/openfoam/storage/examples/damBreak -parallel
    set +x
    date
    echo "ENDED"
    DURATION=$[ $(date +%s) - ${START} ]
    echo ${DURATION}
